### ISSUE TITLE
Swagger

### ISSUE THREAD

**Issue by LeeGa00** [seo-00/0xarmoury-frontend#10]
- Swagger 적용
- 연결된 PR : #9  
- application.yml 추가
```yml
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
```

```yml
springdoc:
  packages-to-scan: com.armoury.backend
  default-consumes-media-type: application/json;charset=UTF-8 # 기본 consume media type
  default-produces-media-type: application/json;charset=UTF-8 # 기본 produce media type
  swagger-ui:
    path: armoury-ui.html # Swagger UI 경로 => localhost:8080/armoury-ui.html
    tags-sorter: alpha # 태그 정렬 기준
    operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP 메소드순)
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
```
- 참고자료
1. <https://adjh54.tistory.com/72>
